config/routes.rb
Rails.application.routes.draw do
  get 'home/set_cookie'
  get 'home/show_cookie'
  get 'home/delete_cookie'
  get 'answers/index'
  get 'answers/show'
  get 'answers/new'
  get 'answers/edit'
  resources :problems do
    resources :answers
  end

  devise_for :teachers
  root to: 'pages#home'
  devise_for :users

  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :teacher do
   get '/teachers/sign_out' => 'devise/sessions#destroy'
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :problem
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :user
  has_many :answers


  def self.search_by(search_term)
    where("subject LIKE :search_term", search_term: "%#{search_term.downcase}%")
  end
end

app/models/problem_observer.rb
require 'my_logger'
class ProblemObserver < ActiveRecord::Observer
  def after_update(record)
  # use the MyLogger instance method to retrieve the single instance/object of the class
  @logger = MyLogger.instance
  # use the logger to log/record a message about the updated car
  @logger.logInformation("###############Observer Demo:#")
  @logger.logInformation("+++ ProblemObserver: The Problem for
      #{record.user.email} has been updated to:
      - subject: #{record.subject}
      - topic: #{record.topic}
      - question #{record.question} ")
    @logger.logInformation("##############################")
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
         validates :email, presence: true,
                     length: { maximum: 255 },
                     format: { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :problems


      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
      validates :email, presence: true,
                      length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @problem = Problem.find(params[:problem_id])
    @answers = @problem.answers
  end

  def show
    @problem = Problem.find(params[:problem_id])
    @answer = @problem.answers.find(params[:id])
  end

  def new
    @problem = Problem.find(params[:problem_id])
    @answer = @problem.answers.build
  end


  def create
      @problem = Problem.find(params[:problem_id])
      @answer = @problem.answers.build(params.require(:answer).permit(:reply))
      if @answer.save
        redirect_to problem_answer_url(@problem, @answer)
      else
        render :action => "new"
      end
  end


  def edit
    @problem = Problem.find(params[:problem_id])
    @answer = @problem.answers.find(params[:id])
  end


  def update
    @problem = Problem.find(params[:problem_id])
    @answer = Answer.find(params[:id])
    if @answer.update_attributes(params.require(:answer).permit(:reply))
      redirect_to problem_answer_url(@problem, @answer)
    else
      render :action => "edit"
    end
  end


  def destroy
    @problem = Problem.find(params[:problem_id])
    @answer = Answer.find(params[:id])
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to problem_answers_path(@problem) }
      format.xml { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def set_cookie
    cookies.permanent.signed[:user_name] = "Sam"
    cookies.permanent.signed[:staff_number] = "0421"
  end

  def show_cookie
    @user_name = cookies[:user_name]
    @user_number = cookies[:staff_number]
  end

  def delete_cookie
    cookies.delete :user_name
    cookies.delete :user_number
  end

  def ping
  end

  def pong
  end

  def index
  end

  private
  def set_breadcrumbs
    if session[:breadcrumbs]
      @breadcrumbs = session[:breadcrumbs]
    else
      @breadcrumbs = Array.new
    end

    @breadcrumbs.push(request.url)

    if @breadcrumbs.count >4
      @breadcrumbs.shift
    end

    session[:breadcrumbs] = @breadcrumbs
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end


end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  require 'my_logger'
  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
    if params[:search]
      @search_term = params[:search]
      @problems = @problems.search_by(@search_term)
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
  end

  # GET /problems/new
  def new
    @problem = current_user.problems.build
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = current_user.problems.build(problem_params)
    logger = MyLogger.instance
     logger.logInformation("A new question was asked: " + @problem.question)
    @problem.user = current_user
    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html { render :new }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    @problem.subject = params[:problem][:subject]
    @problem.topic = params[:problem][:topic]
    @problem.question = params[:problem][:question]
    updated_information = {
      "subject" => @problem.subject,
      "topic" => @problem.topic,
      "question" => @problem.question
    }
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem.destroy
    respond_to do |format|
      format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def problem_params
      params.require(:problem).permit(:subject, :topic, :question)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_problems = @user.problems
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for([@problem, @answer]) do |f| %>
<% if @answer.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@answer.errors.count, "error")%>
prohibited this answer from being saved:</h2>
<ul>
<% @answer.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
<p>
<%= f.label :Reply %><br />
<%= f.text_field :reply %>
</p>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answers</h1>
<%= render 'form' %>
<%= link_to 'Show', problem_answer_path(@problem, @answer) %> |
<%= link_to 'Back', problem_answers_path(@problem) %>

app/views/answers/index.html.erb
<div class="main-nav">
<h1>Answers in <%= @problem.subject %></h1>
<table>
<tr>
<th>Answer reply</th>
</tr>
<% for answer in @answers %>
<tr>
<td><%= answer.reply %></td>
<td><%= link_to 'Show', problem_answer_path(@problem, answer)
%></td>
<% if current_teacher %>
  <td><%= link_to 'Edit', edit_problem_answer_path(@problem, answer)
  %></td>
  <td><%= link_to 'Destroy', problem_answer_path(@problem, answer),
  :confirm => 'Are you sure?', :method => :delete %></td>
<% end %>
</tr>
<% end %>
</table>

<%= link_to 'New answer', new_problem_answer_path(@problem) %>
<%= link_to 'Back to problem', @problem %>
</div>

app/views/answers/new.html.erb
<h1>New Answer</h1>
<%= render 'form' %>
<%= link_to 'Back', problem_answers_path(@problem) %>

app/views/answers/show.html.erb
<h1>Answer in <%= @problem.subject %></h1>
<p>
<b>answer reply:</b>
<%= @answer.reply %>
</p>
<%= link_to 'Edit', edit_problem_answer_path(@problem, @answer) %> |
<%= link_to 'Back', problem_answers_path(@problem) %>

app/views/home/delete_cookie.html.erb
<h1>Home#delete_cookie</h1>
<p>Find me in app/views/home/delete_cookie.html.erb</p>

app/views/home/pong.html.erb
<html> 
<% if @breadcrumbs && @breadcrumbs.any %>
<h3> History </h3>
<ul>
  <% @breadcrumbs[0..2].each do |breadcrumb|%>
  <li><%= link_to breadcrumb, breadcrumb %> </li>
  <%end%>
</ul>
<% end %>
<body>
<%= yield %>
</body>
</html>

app/views/home/set_cookie.html.erb
<h1>Home#set_cookie</h1>
<p>Find me in app/views/home/set_cookie.html.erb</p>

app/views/home/show_cookie.html.erb
<h1>Home#show_cookie</h1>
<table>
  <tr>
    <td> User Name: </td>
    <td><%= @user_name %> </td>
  </tr>
  <tr>
    <td> User Number: </td>
    <td><%= @user_number %> </td>
  </tr>
</table>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <nav class="navbar navbar-light bg-light">
    <% if current_user && current_user.admin %>
      <a class="navbar-brand" <%= link_to 'Teacher Sign up', new_teacher_registration_path %></a>
      <a class="navbar-brand" <%= link_to 'User Sign out', destroy_user_session_path, method: :delete %></a>
    <% elsif current_user %>
      <a class="navbar-brand" <%= link_to 'User Sign out', destroy_user_session_path, method: :delete %></a>
    <% elsif current_teacher %>
      <a class="navbar-brand" <%= link_to 'Teacher Sign out', destroy_teacher_session_path, method: :delete %></a>
    <% else %>
      <a class="navbar-brand" <%= link_to 'User Sign up', new_user_registration_path %></a>
      <a class="navbar-brand" <%= link_to 'User Sign in', new_user_session_path %></a>
      <a class="navbar-brand" <%= link_to 'Teacher Sign in', new_teacher_session_path %></a>
    <% end %>
    <a class="navbar-brand" <%= link_to 'Problems', problems_path %></a>
  </nav>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolSys</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-narrow">
  <div class="masthead">
    <%= render 'layouts/user_header' %>
    <h3 class="muted"><%= link_to "School Home", root_path %></h3>
  </div>
  <hr />
  <%= render 'layouts/alerts' %>
  <%= yield %>
</div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>School System</h1>
<div class="jumbotron">
  <% if user_signed_in? %>
    <h1>Welcome back <%= current_user.email.split('@')[0].capitalize %></h1>

    <p class="lead">
      Welcome to Online School!! Come on in and have some fun!
    </p>
    <a class="navbar-brand" <%= link_to 'User Sign out', destroy_user_session_path, method: :delete %></a>
    <a class="navbar-brand" <%= link_to 'Problems', problems_path %></a>
    <a class="navbar-brand" <%= link_to "Profile", user_path(current_user) %></a>

  <% else %>
    <h1>Welcome! Come and Sign in!</h1>

  <% end %>

</div>

app/views/problems/_form.html.erb
<%= form_with(model: problem, local: true) do |form| %>
  <% if problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
        <% problem.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :topic %>
    <%= form.text_field :topic %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Problems</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Topic</th>
      <th>Question</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <h2> Search</h2>
  <div class="searchingclass">
    <form class="search"
    <%= form_for "", url: problems_path, role: "search", method: :get do %>
    <%= text_field_tag :search, @search_term, placeholder: "Search..." %>
    <%= submit_tag "Search" %>
    <% end %>
    </form>
  </div>

  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= problem.subject %></td>
        <td><%= problem.topic %></td>
        <td><%= problem.question %></td>
        <td><%= problem.user.email.split('@')[0].capitalize %></td>
        <td><%= link_to 'Show', problem %></td>
        <% if current_user && current_user.admin || current_teacher %>
        <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
        <td><%= button_to "destroy", problem, :method => :delete, data: { confirm: 'Are you sure?' }, class: "btn-danger delete-btn" %></td>
        <% end %>
      </tr>
    <% end %>
    <td><%= link_to 'New Problem', new_problem_path %></td>
    <td><%= link_to 'Home Page', root_path %></td>
  </tbody>
</table>

app/views/problems/new.html.erb
<h1>New Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<div class="answers"
<p>
  <strong>Subject:</strong>
  <%= @problem.subject %>
</p>
<p>
  <strong>Topic:</strong>
  <%= @problem.topic %>
</p>
<p>
  <strong>Question:</strong>
  <%= @problem.question %>
</p>

<p>
  <strong>User:</strong>
  <%= @problem.user.email.split('@')[0].capitalize %>
</p>

<h2>Answers</h2>
<% @problem.answers.each do |answer| %>
<p>
  <b>Answer reply:</b>
  <%= answer.reply %>
</p>
<% end %>
<%= link_to 'Edit problem', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %> |
<%= link_to 'Show Answers', problem_answers_path(@problem) %>
</div>

app/views/users/show.html.erb
<div class="problems">
<h1 class="profile"><%= @user.email.split('@')[0].capitalize%>'s Profile Page</h1>

  <% @user_problems.each do |problem| %>
    <%= link_to problem.question, problem_path(problem) %>
  <% end %>
</div>